Add onTap and closeOnTap methods
koukibadr/Elegant-Notification pull request #105
Opened 2024-02-03 16:33 UTC by ferraridamiano

Hi there!
This PR adds a couple of useful properties to this package:

- `onTap` let the user click on the whole notification. A developer cannot set both an action and onTap
- `closeOnTap` is a property that if set to true closes the notification on user interaction (onTap or action pressed)

Thanks for this package, it is very useful. Now I only miss the swipe to remove gesture on the notification. Thanks for moving the packege to MIT license

2024-02-04 10:13 UTC, koukibadr requested changes
According to the changes when `closeOnTap  == true` but `onTap` is null the closeOnTap won't work properly (it won't close the popup)
I propose you update the InkWell widget as below
```
InkWell(
        onTap:() {
                widget.onTap?.call();
                if (widget.closeOnTap) {
                  closeNotification();
                }
              },
```

2024-02-04 10:20 UTC, ferraridamiano commented
`closeOnTap` is meant to be only on user iteraction, i.e. only when `onTap `or an `action` are pressed. If there is no action or tap event associated with it, it should not close. What do you think about it?

2024-02-05 08:19 UTC, koukibadr commented
> `closeOnTap` is meant to be only on user iteraction, i.e. only when `onTap `or an `action` are pressed. If there is no action or tap event associated with it, it should not close. What do you think about it?

Let me test it first this evening and then we merge it and publish a new version

2024-02-21 18:55 UTC, koukibadr approved these changes

2024-02-21 18:55 UTC, merged